export const ALL_PRODUCTS_REQUET = 'ALL_PRODUCTS_REQUET'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
